name: Node.js CI
on:
  push:
    branches: [ v2 ]
  pull_request:
    branches: [ v2 ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Run tests on ${{ matrix.os }}, Node ${{ matrix.node-version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        node-version: [ 16 ]
        include:
        - os: ubuntu-latest
          node-version: 12
        - os: ubuntu-latest
          node-version: 14
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint
    - run: npm run build
    - run: npm run test -- --workers=1
    - run: npx vsce package
    - uses: actions/upload-artifact@v2
      if: matrix.os == 'ubuntu-latest' && matrix.node-version == '16'
      with:
        name: vsc-extension
        path: "*.vsix"
        retention-days: 30
